site_name: WM Docs                                # Nome visualizzato nel titolo del sito
site_url: https://cyberfolk.github.io/wm-docs     # URL pubblico del sito generato
repo_url: https://github.com/cyberfolk/wm-docs    # URL del repository GitHub (mostrato con un pulsante nell'interfaccia)
repo_name: wm-docs                                # Nome breve mostrato nel pulsante repo
site_description: Documentazione del progetto WM  # Metadati del sito (utili per SEO)
site_author: Cyberfolk                            # Metadati del sito (utili per SEO)
edit_uri: edit/main/docs/

extra_css:              # CSS personalizzati da includere
  - styles/extra.css

#extra_javascript:      # JS personalizzati da includere
#  - js/custom.js

# Tema grafico e opzioni Material for MkDocs
theme:
  name: material              # Tema scelto
  language: it                # Lingua dell'interfaccia
  logo: img/logo.svg          # Percorso al logo da mostrare nel titolo del sito
#  favicon: images/logo.ico    # Favicon del sito
  features: # Funzionalità abilitate del tema Material
    - content.code.copy       # Aggiunge pulsante "copia" nei blocchi di codice
    - content.action.edit     # Abilita pulsante "modifica" (richiede configurazione repo)
    - navigation.tabs         # Navigazione a tab
    - navigation.top          # Torna su in alto quando si scrolla
    - toc.integrate           # Integra il sommario nella barra laterale
    - search.highlight        # Evidenziazione del testo cercato
    - content.tabs.link       # Linkabili i contenuti a tab
  palette: # Colori per modalità chiara/scura
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue

# Plugin attivi
plugins:
  - search                     # Ricerca interna
  - encryptcontent:            # Protezione dei contenuti con password (plugin aggiuntivo)
      title_prefix: "[DM] "    # Prefisso del titolo per le pagine criptate
      global_password: null    # Nessuna password globale: ogni pagina può avere la sua
  - redirects:
      redirect_maps:
        index.md: base/B00-preview.md

# Estensioni Markdown abilitate (espandono le funzionalità dei .md)
markdown_extensions:
  - admonition                 # Blocchi "attenzione", "nota", "avviso" ecc.
  - pymdownx.details           # Blocchi a scomparsa (tipo <details>)
  - pymdownx.superfences       # Supporto avanzato per blocchi di codice
  - pymdownx.tabbed:
      alternate_style: true    # Stile alternativo per i contenuti a tab
  - pymdownx.highlight         # Evidenziazione sintassi codice
  - pymdownx.inlinehilite      # Evidenziazione inline nei testi
  - pymdownx.emoji             # Supporto emoji (es. `:rocket:`)
  - pymdownx.keys              # Visualizzazione combinazioni di tasti (es. `⌘ + C`)
  - pymdownx.tasklist          # Checkbox in stile lista attività `[ ]`, `[x]`

# Struttura della navigazione
nav:
  - Home:
      - "Presentazione": base/B00-preview.md
      - "Dichiarazione d'intenti": base/B01-ddi.md
      - "Creazione PG": base/B02-creazione-pg.md
      - "BG d'esempio": base/B03-bg-list.md
  - "Esplorazione": exploration/E00-esplorazione.md
  - DM:
      - "Trama": dm/D00-trama.md
      - "Struttura Finemondo": dm/D01-struttura-finemondo.md
      - "Abitanti Finemondo": dm/D02-abitanti-finemondo.md
      - "Squadre E ed Eterno M": dm/D03-squadra-eletta-eterno-malvagio.md
      - "Domande PG → Eterno": dm/D04-domande-pg-eterno.md
      - "Regioni": dm/D05-regioni.md
      - "Problematiche": dm/D99-problematiche.md
  - "Extra":
      - "Gettoni Arcani": extra/X00-gettoni-arcani.md
      - "PX e PX%": extra/X01-px-px%.md
      - "Tier 5E → Titoli WM": extra/X02-tier.md
      - "Scratchs": extra/scratchs.md

# Contenuti extra, es. social link e footer
extra:
  social:
    - icon: fontawesome/brands/github  # Icona GitHub
      link: https://github.com/cyberfolk  # Copyright nel footer (usa entità HTML per compatibilità YAML)
copyright: "Copyright &copy; 2025 Andrea"
