# ======================================================================================================================
site_name: Echi Dal Finimondo                     # Nome visualizzato nel titolo del sito
site_url: https://cyberfolk.github.io/wm-docs     # URL pubblico del sito generato
repo_url: https://github.com/cyberfolk/wm-docs    # URL del repository GitHub (mostrato con pulsante nell'interfaccia)
repo_name: wm-docs                                # Nome breve mostrato nel pulsante repo
site_description: Documentazione del progetto WM  # Metadati del sito (utili per SEO)
site_author: Cyberfolk                            # Metadati del sito (utili per SEO)
edit_uri: edit/main/docs/
# ======================================================================================================================
use_directory_urls: true    # Toglie .html dagli url di produzione (url produzione = url locale)
# ======================================================================================================================
extra_css:              # CSS personalizzati da includere
  - styles/extra.css
extra_javascript:       # JS  personalizzati da includere
  - js/custom.js
# ======================================================================================================================
# Tema grafico e opzioni Material for MkDocs
theme:
  name: material              # Tema scelto
  language: it                # Lingua dell'interfaccia
  logo: img/logo.svg          # Percorso al logo da mostrare nel titolo del sito
  favicon: img/favicon.ico    # Favicon del sito
  features: # Funzionalità abilitate del tema Material
    - content.code.copy       # Aggiunge pulsante "copia" nei blocchi di codice
    - content.action.edit     # Abilita pulsante "modifica" (richiede configurazione repo)
    - navigation.tabs         # Navigazione a tab
    - navigation.top          # Torna su in alto quando si scrolla
    - toc.integrate           # Integra il sommario nella barra laterale
    - search.highlight        # Evidenziazione del testo cercato
    - content.tabs.link       # Linkabili i contenuti a tab
  palette: # Colori per modalità chiara/scura
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
# ======================================================================================================================
# Plugin attivi
plugins:
  - search                     # Ricerca interna
  - encryptcontent: # Protezione dei contenuti con password (plugin aggiuntivo)
      title_prefix: "[DM] "    # Prefisso del titolo per le pagine criptate
      global_password: null    # Nessuna password globale: ogni pagina può avere la sua
  - redirects:
      redirect_maps:
        index.md: md/base/b00-preview.md
# ======================================================================================================================
# Estensioni Markdown abilitate (espandono le funzionalità dei .md)
markdown_extensions:
  - admonition                 # Blocchi "attenzione", "nota", "avviso" ecc.
  - pymdownx.details           # Blocchi a scomparsa (tipo <details>)
  - pymdownx.superfences       # Supporto avanzato per blocchi di codice
  - pymdownx.tabbed:
      alternate_style: true    # Stile alternativo per i contenuti a tab
  - pymdownx.highlight         # Evidenziazione sintassi codice
  - pymdownx.inlinehilite      # Evidenziazione inline nei testi
  - pymdownx.emoji             # Supporto emoji (es. `:rocket:`)
  - pymdownx.keys              # Visualizzazione combinazioni di tasti (es. `⌘ + C`)
  - pymdownx.tasklist          # Checkbox in stile lista attività `[ ]`, `[x]`
# ======================================================================================================================
# Struttura della navigazione
nav:
  - Player:
      - "Presentazione": md/base/b00-preview.md
      - "Maggiori dettagli": md/base/b01-ddi.md
      - "Creazione PG": md/base/b02-creazione-pg.md
      - "BG d'esempio": md/base/b03-bg-list.md
      - "Esplorazione": md/base/b04-esplorazione.md
  - DM:
      - "Presentazione": md/dm/d00-preview.md
      - "Macro Trama": md/dm/d01-trama.md
      - "Struttura Finimondo": md/dm/d02-finimondo-struttura.md
      - "Abitanti Finimondo": md/dm/d03-finimondo-abitanti.md
      - "Squadre E ed Eterno M": md/dm/d04-squadra-eletta-eterno-malvagio.md
      - "Domande PG → Eterno": md/dm/d05-domande-pg-eterno.md
      - "Regioni": md/dm/d06-regioni.md
      - "Domande Aperte": md/dm/d07-domande-aperte.md
      - "Layer di Lore": md/dm/d08-layer-lore.md
      - "Lore Atomizzata": md/dm/d09-lore-atomizzata.md
      - "Problematiche": md/dm/d99-problematiche.md
  - "Extra":
      - "Presentazione": md/extra/x00-preview.md
      - "Gettoni Arcani": md/extra/x01-gettoni-arcani.md
      - "PX e PX%": md/extra/x02-px-px%.md
      - "Tier 5E → Titoli WM": md/extra/x03-tier.md
      - "Trappole": md/extra/x05-traps.md
      - "Scratchs": md/extra/x99-scratches.md
  - "Narratologia":
      - "Presentazione": md/lore-tool/l00-preview.md
      - "Fazioni": md/lore-tool/l01-fazioni.md
      - "Insediamenti": md/lore-tool/l02-insediamenti.md
      - "NPCs": md/lore-tool/l03-npcs.md
      - "HEXs | Regioni": md/lore-tool/l10n-hex.md
      - "POI | Punto d’Interesse": md/lore-tool/l04-poi.md
      - "ML | Mostro Leggendario": md/lore-tool/l07-monster.md
      - "Quest": md/lore-tool/l06-quest.md
      - "Artefatto": md/lore-tool/l08-artifact.md
      - "Lore Item": md/lore-tool/l05-lore-item.md
      - "RN | Relazione Narrativa": md/lore-tool/l09-relation.md
# ======================================================================================================================
# Contenuti extra, es. social link e footer
extra:
  social:
    - icon: fontawesome/brands/github  # Icona GitHub
      link: https://github.com/cyberfolk  # Copyright nel footer (usa entità HTML per compatibilità YAML)
# ======================================================================================================================
copyright: "Copyright &copy; 2025 Cyberfolk"
# ======================================================================================================================
